spring.application.name=estudiantes

spring.datasource.url=jdbc:postgresql://localhost:5432/estudiantes_db
spring.datasource.username=postgres
spring.datasource.password=Ismael2003Andrade
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

server.port=8081

server.error.include-stacktrace=always
server.error.include-message=always

logging.file.name=app.log
logging.level.com.microservicio.estudiantes=DEBUG
logging.level.org.springframework.web=DEBUG
